-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.questao
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 ),
    questao character varying NOT NULL,
    formato character varying DEFAULT 'Multipla Escolha',
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.resposta
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 ),
    resposta character varying NOT NULL,
    resposta_correta boolean NOT NULL,
    id_questao bigint NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.resposta
    ADD FOREIGN KEY (id_questao)
    REFERENCES public.questao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;